{

    TLegend *l = new TLegend(.7,.75,.89,.89);

    TFile f1("Bkg_B0ToPsiMuMu_0004.root");

    TCanvas *c11 = new TCanvas("c11","c11",1050,1050);
    //gPad-> SetLogy();
    //hjpsiKPiMassBaseSelAlt->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt->SetMinimum(1);
    //hjpsiKPiMassNoPhi->SetMaximum(17000);
    hjpsiKPiMassNoPhi->SetMinimum(1);
    hjpsiKPiMassBaseSelAlt->Draw();
    hjpsiKPiMassNoPhi->SetLineColor(kRed);
    hjpsiKPiMassNoPhi->Draw("same");
    hjpsiKPiMassNoPhi_discard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard->Draw("same");
    
    TLegend *l = new TLegend(.60,.60,.89,.73);
    l->AddEntry(hjpsiKPiMassBaseSelAlt,"before Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi,"after Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi_discard, "Rejected events", "F");
    l->SetBorderSize(0);
    l->SetTextSize(0.025);
    l->Draw();
    c11->SaveAs("Bkg_B0_MuMuPiK_compare.png");
    gPad-> SetLogy();
    c11->SaveAs("Bkg_B0_MuMuPiK_compare_log.png");
    
    TCanvas *c12 = new TCanvas("c12","c12",1050,1050);
    hjpsiKKMassBaseSelAlt->SetMinimum(1);
    hjpsiKKMassBaseSelAlt->Draw();
    c12->SaveAs("Bkg_B0_MuMuKK.png");
    TCanvas *c13 = new TCanvas("c13","c13",1050,1050);
    hjpsiPiPiMassBaseSelAlt->SetMinimum(1);
    hjpsiPiPiMassBaseSelAlt->Draw();
    c13->SaveAs("Bkg_B0_MuMuPiPi.png");
    TCanvas *c14 = new TCanvas("c14","c14",1050,1050);
    hjpsiKProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiKProtonMassBaseSelAlt->Draw();
    c14->SaveAs("Bkg_B0_MuMuKProton.png");
    TCanvas *c15 = new TCanvas("c15","c15",1050,1050);
    hjpsiPiProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiPiProtonMassBaseSelAlt->Draw();
    c15->SaveAs("Bkg_B0_MuMuPiProton.png");
    TCanvas *c16 = new TCanvas("c16","c16",1050,1050);
    Int_t bxmax=hKPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass->GetXaxis()->FindBin(0.0);
    hKPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass->Draw();
    hKPiMass_peak->SetLineColor(kRed);
    hKPiMass_peak->Draw("same");
    TLegend *ll = new TLegend(.60,.60,.89,.73);
    ll->AddEntry(hKPiMass,"All entries","L");
    ll->AddEntry(hKPiMass_peak,"under B0 peak","L");
    ll->SetBorderSize(0);
    ll->SetTextSize(0.025);
    ll->Draw();
    c16->SaveAs("Bkg_B0_KPi_all.png");
    TCanvas *c17 = new TCanvas("c17","c17",1050,1050);
    Int_t bxmax=hPiPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass->GetXaxis()->FindBin(0.0);
    hPiPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass->Draw();
    hPiPiMass_peak->SetLineColor(kRed);
    hPiPiMass_peak->Draw("same");
    ll->Draw();
    c17->SaveAs("Bkg_B0_PiPi_all.png");
    TCanvas *c18 = new TCanvas("c18","c18",1050,1050);
    Int_t bxmax=hKKMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass->GetXaxis()->FindBin(0.0);
    hKKMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass->Draw();
    hKKMass_peak->SetLineColor(kRed);
    hKKMass_peak->Draw("same");
    ll->Draw();
    c18->SaveAs("Bkg_B0_KK_all.png");
    TCanvas *c19 = new TCanvas("c19","c19",1050,1050);
    Int_t bxmax=hKProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass->GetXaxis()->FindBin(0.0);
    hKProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass->Draw();
    hKProtonMass_peak->SetLineColor(kRed);
    hKProtonMass_peak->Draw("same");
    ll->Draw();
    c19->SaveAs("Bkg_B0_KProton_all.png");
    TCanvas *c110 = new TCanvas("c110","c110",1050,1050);
    Int_t bxmax=hPiProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass->GetXaxis()->FindBin(0.0);
    hPiProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass->Draw();
    hPiProtonMass_peak->SetLineColor(kRed);
    hPiProtonMass_peak->Draw("same");
    ll->Draw();
    c110->SaveAs("Bkg_B0_PiProton_all.png");
    TCanvas *c111 = new TCanvas("c111","c111",1050,1050);
    Int_t bxmax=hKPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak->GetXaxis()->FindBin(0.0);
    hKPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak->Draw();
    c111->SaveAs("Bkg_B0_KPi_peak.png");
    TCanvas *c112 = new TCanvas("c112","c112",1050,1050);
    Int_t bxmax=hPiPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak->Draw();
    c112->SaveAs("Bkg_B0_PiPi_peak.png");
    TCanvas *c113 = new TCanvas("c113","c113",1050,1050);
    Int_t bxmax=hKKMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak->GetXaxis()->FindBin(0.0);
    hKKMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak->Draw();
    c113->SaveAs("Bkg_B0_KK_peak.png");
    TCanvas *c114 = new TCanvas("c114","c114",1050,1050);
    Int_t bxmax=hKProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak->Draw();
    c114->SaveAs("Bkg_B0_KProton_peak.png");
    TCanvas *c115 = new TCanvas("c115","c115",1050,1050);
    Int_t bxmax=hPiProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak->Draw();
    c115->SaveAs("Bkg_B0_PiProton_peak.png");
    
    TCanvas *c116 = new TCanvas("c116","c116",1050,1050);
    hJpsiKPi_JpsiKKBaseSelAlt->Draw("colz");
    c116->SaveAs("Bkg_B0_JpsiKPi_JpsiKK.png");
    TCanvas *c117 = new TCanvas("c117","c117",1050,1050);
    hJpsiKPi_JpsiPiPiBaseSelAlt->Draw("colz");
    c117->SaveAs("Bkg_B0_JpsiKPi_JpsiPiPi.png");
    TCanvas *c118 = new TCanvas("c118","c118",1050,1050);
    hJpsiKPi_JpsiPiProtonBaseSelAlt->Draw("colz");
    c118->SaveAs("Bkg_B0_JpsiKPi_JpsiPiProton.png");
    TCanvas *c119 = new TCanvas("c119","c119",1050,1050);
    hJpsiKPi_JpsiKProtonBaseSelAlt->Draw("colz");
    c119->SaveAs("Bkg_B0_JpsiKPi_JpsiKProton.png");
    f1->Close();
    
    TFile f2("Bkg_BpToPsiMuMu_0000.root");
    TCanvas *c21 = new TCanvas("c21","c21",1050,1050);
    //hjpsiKPiMassBaseSelAlt->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt->SetMinimum(1);
    //hjpsiKPiMassNoPhi->SetMaximum(17000);
    hjpsiKPiMassNoPhi->SetMinimum(1);
    hjpsiKPiMassBaseSelAlt->Draw();
    hjpsiKPiMassNoPhi->SetLineColor(kRed);
    hjpsiKPiMassNoPhi->Draw("same");
    hjpsiKPiMassNoPhi_discard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard->Draw("same");
    l->Draw();
    c21->SaveAs("Bkg_Bp_MuMuPiK_compare.png");
    gPad-> SetLogy();
    c21->SaveAs("Bkg_Bp_MuMuPiK_compare_log.png");
    TCanvas *c22 = new TCanvas("c22","c22",1050,1050);
    hjpsiKKMassBaseSelAlt->SetMinimum(1);
    hjpsiKKMassBaseSelAlt->Draw();
    c22->SaveAs("Bkg_Bp_MuMuKK.png");
    TCanvas *c23 = new TCanvas("c23","c23",1050,1050);
    hjpsiPiPiMassBaseSelAlt->SetMinimum(1);
    hjpsiPiPiMassBaseSelAlt->Draw();
    c23->SaveAs("Bkg_Bp_MuMuPiPi.png");
    TCanvas *c24 = new TCanvas("c24","c24",1050,1050);
    hjpsiKProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiKProtonMassBaseSelAlt->Draw();
    c24->SaveAs("Bkg_Bp_MuMuKProton.png");
    TCanvas *c25 = new TCanvas("c25","c25",1050,1050);
    hjpsiPiProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiPiProtonMassBaseSelAlt->Draw();
    c25->SaveAs("Bkg_Bp_MuMuPiProton.png");
    TCanvas *c26 = new TCanvas("c26","c26",1050,1050);
    Int_t bxmax=hKPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass->GetXaxis()->FindBin(0.0);
    hKPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass->Draw();
    hKPiMass_peak->SetLineColor(kRed);
    hKPiMass_peak->Draw("same");
    ll->Draw();
    c26->SaveAs("Bkg_Bp_KPi_all.png");
    TCanvas *c27 = new TCanvas("c27","c27",1050,1050);
    Int_t bxmax=hPiPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass->GetXaxis()->FindBin(0.0);
    hPiPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass->Draw();
    hPiPiMass_peak->SetLineColor(kRed);
    hPiPiMass_peak->Draw("same");
    ll->Draw();
    c27->SaveAs("Bkg_Bp_PiPi_all.png");
    TCanvas *c28 = new TCanvas("c28","c28",1050,1050);
    Int_t bxmax=hKKMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass->GetXaxis()->FindBin(0.0);
    hKKMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass->Draw();
    hKKMass_peak->SetLineColor(kRed);
    hKKMass_peak->Draw("same");
    ll->Draw();
    c28->SaveAs("Bkg_Bp_KK_all.png");
    TCanvas *c29 = new TCanvas("c29","c29",1050,1050);
    Int_t bxmax=hKProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass->GetXaxis()->FindBin(0.0);
    hKProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass->Draw();
    hKProtonMass_peak->SetLineColor(kRed);
    hKProtonMass_peak->Draw("same");
    ll->Draw();
    c29->SaveAs("Bkg_Bp_KProton_all.png");
    TCanvas *c210 = new TCanvas("c210","c210",1050,1050);
    Int_t bxmax=hPiProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass->GetXaxis()->FindBin(0.0);
    hPiProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass->Draw();
    hPiProtonMass_peak->SetLineColor(kRed);
    hPiProtonMass_peak->Draw("same");
    ll->Draw();
    c210->SaveAs("Bkg_Bp_PiProton_all.png");
    TCanvas *c211 = new TCanvas("c211","c211",1050,1050);
    Int_t bxmax=hKPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak->GetXaxis()->FindBin(0.0);
    hKPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak->Draw();
    c211->SaveAs("Bkg_Bp_KPi_peak.png");
    TCanvas *c212 = new TCanvas("c212","c212",1050,1050);
    Int_t bxmax=hPiPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak->Draw();
    c212->SaveAs("Bkg_Bp_PiPi_peak.png");
    TCanvas *c213 = new TCanvas("c213","c213",1050,1050);
    Int_t bxmax=hKKMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak->GetXaxis()->FindBin(0.0);
    hKKMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak->Draw();
    c213->SaveAs("Bkg_Bp_KK_peak.png");
    TCanvas *c214 = new TCanvas("c214","c214",1050,1050);
    Int_t bxmax=hKProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak->Draw();
    c214->SaveAs("Bkg_Bp_KProton_peak.png");
    TCanvas *c215 = new TCanvas("c215","c215",1050,1050);
    Int_t bxmax=hPiProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak->Draw();
    c215->SaveAs("Bkg_Bp_PiProton_peak.png");
    f2->Close();

    
    
    TFile f3("Bkg_BsToPsiMuMu_0001.root");
    TCanvas *c31 = new TCanvas("c31","c31",1050,1050);
    //hjpsiKPiMassBaseSelAlt->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt->SetMinimum(1);
    //hjpsiKPiMassNoPhi->SetMaximum(17000);
    hjpsiKPiMassNoPhi->SetMinimum(1);
    hjpsiKPiMassBaseSelAlt->Draw();
    hjpsiKPiMassNoPhi->SetLineColor(kRed);
    hjpsiKPiMassNoPhi->Draw("same");
    hjpsiKPiMassNoPhi_discard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard->Draw("same");
    l->Draw();
    c31->SaveAs("Bkg_Bs_MuMuPiK_compare.png");
    gPad-> SetLogy();
    c31->SaveAs("Bkg_Bs_MuMuPiK_compare_log.png");
    TCanvas *c32 = new TCanvas("c32","c32",1050,1050);
    hjpsiKKMassBaseSelAlt->SetMinimum(1);
    hjpsiKKMassBaseSelAlt->Draw();
    c32->SaveAs("Bkg_Bs_MuMuKK.png");
    TCanvas *c33 = new TCanvas("c33","c33",1050,1050);
    hjpsiPiPiMassBaseSelAlt->SetMinimum(1);
    hjpsiPiPiMassBaseSelAlt->Draw();
    c33->SaveAs("Bkg_Bs_MuMuPiPi.png");
    TCanvas *c34 = new TCanvas("c34","c34",1050,1050);
    hjpsiKProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiKProtonMassBaseSelAlt->Draw();
    c34->SaveAs("Bkg_Bs_MuMuKProton.png");
    TCanvas *c35 = new TCanvas("c35","c35",1050,1050);
    hjpsiPiProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiPiProtonMassBaseSelAlt->Draw();
    c35->SaveAs("Bkg_Bs_MuMuPiProton.png");
    TCanvas *c36 = new TCanvas("c36","c36",1050,1050);
    Int_t bxmax=hKPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass->GetXaxis()->FindBin(0.0);
    hKPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass->Draw();
    hKPiMass_peak->SetLineColor(kRed);
    hKPiMass_peak->Draw("same");
    ll->Draw();
    c36->SaveAs("Bkg_Bs_KPi_all.png");
    TCanvas *c37 = new TCanvas("c37","c37",1050,1050);
    Int_t bxmax=hPiPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass->GetXaxis()->FindBin(0.0);
    hPiPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass->Draw();
    hPiPiMass_peak->SetLineColor(kRed);
    hPiPiMass_peak->Draw("same");
    ll->Draw();
    c37->SaveAs("Bkg_Bs_PiPi_all.png");
    TCanvas *c38 = new TCanvas("c38","c38",1050,1050);
    Int_t bxmax=hKKMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass->GetXaxis()->FindBin(0.0);
    hKKMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass->Draw();
    hKKMass_peak->SetLineColor(kRed);
    hKKMass_peak->Draw("same");
    ll->Draw();
    c38->SaveAs("Bkg_Bs_KK_all.png");
    TCanvas *c39 = new TCanvas("c39","c39",1050,1050);
    Int_t bxmax=hKProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass->GetXaxis()->FindBin(0.0);
    hKProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass->Draw();
    hKProtonMass_peak->SetLineColor(kRed);
    hKProtonMass_peak->Draw("same");
    ll->Draw();
    c39->SaveAs("Bkg_Bs_KProton_all.png");
    TCanvas *c310 = new TCanvas("c310","c310",1050,1050);
    Int_t bxmax=hPiProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass->GetXaxis()->FindBin(0.0);
    hPiProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass->Draw();
    hPiProtonMass_peak->SetLineColor(kRed);
    hPiProtonMass_peak->Draw("same");
    ll->Draw();
    c310->SaveAs("Bkg_Bs_PiProton_all.png");
    TCanvas *c311 = new TCanvas("c311","c311",1050,1050);
    Int_t bxmax=hKPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak->GetXaxis()->FindBin(0.0);
    hKPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak->Draw();
    c311->SaveAs("Bkg_Bs_KPi_peak.png");
    TCanvas *c312 = new TCanvas("c312","c312",1050,1050);
    Int_t bxmax=hPiPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak->Draw();
    c312->SaveAs("Bkg_Bs_PiPi_peak.png");
    TCanvas *c313 = new TCanvas("c313","c313",1050,1050);
    Int_t bxmax=hKKMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak->GetXaxis()->FindBin(0.0);
    hKKMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak->Draw();
    c313->SaveAs("Bkg_Bs_KK_peak.png");
    TCanvas *c314 = new TCanvas("c314","c314",1050,1050);
    Int_t bxmax=hKProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak->Draw();
    c314->SaveAs("Bkg_Bs_KProton_peak.png");
    TCanvas *c315 = new TCanvas("c315","c315",1050,1050);
    Int_t bxmax=hPiProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak->Draw();
    c315->SaveAs("Bkg_Bs_PiProton_peak.png");
    f3->Close();
    
    TFile f4("Bkg_LambdaBToPsiMuMu.root");
    TCanvas *c41 = new TCanvas("c41","c41",1050,1050);
    //hjpsiKPiMassBaseSelAlt->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt->SetMinimum(1);
    //hjpsiKPiMassNoPhi->SetMaximum(17000);
    hjpsiKPiMassNoPhi->SetMinimum(1);
    hjpsiKPiMassBaseSelAlt->Draw();
    hjpsiKPiMassNoPhi->SetLineColor(kRed);
    hjpsiKPiMassNoPhi->Draw("same");
    hjpsiKPiMassNoPhi_discard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard->Draw("same");
    l->Draw();
    c41->SaveAs("Bkg_LambdaB_MuMuPiK_compare.png");
    gPad-> SetLogy();
    c41->SaveAs("Bkg_LambdaB_MuMuPiK_compare_log.png");
    TCanvas *c42 = new TCanvas("c42","c42",1050,1050);
    hjpsiKKMassBaseSelAlt->SetMinimum(1);
    hjpsiKKMassBaseSelAlt->Draw();
    c42->SaveAs("Bkg_LambdaB_MuMuKK.png");
    TCanvas *c43 = new TCanvas("c43","c43",1050,1050);
    hjpsiPiPiMassBaseSelAlt->SetMinimum(1);
    hjpsiPiPiMassBaseSelAlt->Draw();
    c43->SaveAs("Bkg_LambdaB_MuMuPiPi.png");
    TCanvas *c44 = new TCanvas("c44","c44",1050,1050);
    hjpsiKProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiKProtonMassBaseSelAlt->Draw();
    c44->SaveAs("Bkg_LambdaB_MuMuKProton.png");
    TCanvas *c45 = new TCanvas("c45","c45",1050,1050);
    hjpsiPiProtonMassBaseSelAlt->SetMinimum(1);
    hjpsiPiProtonMassBaseSelAlt->Draw();
    c45->SaveAs("Bkg_LambdaB_MuMuPiProton.png");
    TCanvas *c46 = new TCanvas("c46","c46",1050,1050);
    Int_t bxmax=hKPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass->GetXaxis()->FindBin(0.0);
    hKPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass->Draw();
    hKPiMass_peak->SetLineColor(kRed);
    hKPiMass_peak->Draw("same");
    ll->Draw();
    c46->SaveAs("Bkg_LambdaB_KPi_all.png");
    TCanvas *c47 = new TCanvas("c47","c47",1050,1050);
    Int_t bxmax=hPiPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass->GetXaxis()->FindBin(0.0);
    hPiPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass->Draw();
    hPiPiMass_peak->SetLineColor(kRed);
    hPiPiMass_peak->Draw("same");
    ll->Draw();
    c47->SaveAs("Bkg_LambdaB_PiPi_all.png");
    TCanvas *c48 = new TCanvas("c48","c48",1050,1050);
    Int_t bxmax=hKKMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass->GetXaxis()->FindBin(0.0);
    hKKMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass->Draw();
    hKKMass_peak->SetLineColor(kRed);
    hKKMass_peak->Draw("same");
    ll->Draw();
    c48->SaveAs("Bkg_LambdaB_KK_all.png");
    TCanvas *c49 = new TCanvas("c49","c49",1050,1050);
    Int_t bxmax=hKProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass->GetXaxis()->FindBin(0.0);
    hKProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass->Draw();
    hKProtonMass_peak->SetLineColor(kRed);
    hKProtonMass_peak->Draw("same");
    ll->Draw();
    c49->SaveAs("Bkg_LambdaB_KProton_all.png");
    TCanvas *c410 = new TCanvas("c410","c410",1050,1050);
    Int_t bxmax=hPiProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass->GetXaxis()->FindBin(0.0);
    hPiProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass->Draw();
    hPiProtonMass_peak->SetLineColor(kRed);
    hPiProtonMass_peak->Draw("same");
    ll->Draw();
    c410->SaveAs("Bkg_LambdaB_PiProton_all.png");
    TCanvas *c411 = new TCanvas("c411","c411",1050,1050);
    Int_t bxmax=hKPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak->GetXaxis()->FindBin(0.0);
    hKPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak->Draw();
    c411->SaveAs("Bkg_LambdaB_KPi_peak.png");
    TCanvas *c412 = new TCanvas("c412","c412",1050,1050);
    Int_t bxmax=hPiPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak->Draw();
    c412->SaveAs("Bkg_LambdaB_PiPi_peak.png");
    TCanvas *c413 = new TCanvas("c413","c413",1050,1050);
    Int_t bxmax=hKKMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak->GetXaxis()->FindBin(0.0);
    hKKMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak->Draw();
    c413->SaveAs("Bkg_LambdaB_KK_peak.png");
    TCanvas *c414 = new TCanvas("c414","c414",1050,1050);
    Int_t bxmax=hKProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak->Draw();
    c414->SaveAs("Bkg_LambdaB_KProton_peak.png");
    TCanvas *c415 = new TCanvas("c415","c415",1050,1050);
    Int_t bxmax=hPiProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak->Draw();
    c415->SaveAs("Bkg_LambdaB_PiProton_peak.png");
    f4->Close();

    
    /*
    
    TCanvas *c11 = new TCanvas("c11","c11",1050,1050);
    hDalitz_peak_bin3->Draw("colz");
    hDalitz_peak_bin3->SetTitle("Dalitz - Peak");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    TCanvas *c12 = new TCanvas("c12","c12",1050,1050);
    c12->cd();
    hDalitz_sideband_bin3->Draw("colz");
    hDalitz_sideband_bin3->SetTitle("Dalitz - Sidebands");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");

    

    TCanvas *c11 = new TCanvas("c11","c11",1050,1050);
    c11->Divide(2,2);

    c11->cd(1);
    hDalitz_peak_bin1->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c12 = new TCanvas("c12","c12",900,700);
    c11->cd(2);
    hDalitz_peak_bin2->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c13 = new TCanvas("c13","c13",900,700);
    c11->cd(3);
    hDalitz_peak_bin3->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c14 = new TCanvas("c14","c14",900,700);
    c11->cd(4);
    hDalitz_peak_bin4->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    
    TCanvas *c21 = new TCanvas("c21","c21",1050,1050);
    c21->Divide(2,2);
    
    c21->cd(1);
    hDalitz_sideband_bin1->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c22 = new TCanvas("c22","c22",900,700);
    c21->cd(2);
    hDalitz_sideband_bin2->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c23 = new TCanvas("c23","c23",900,700);
    c21->cd(3);
    hDalitz_sideband_bin3->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
    
    //TCanvas *c24 = new TCanvas("c24","c24",900,700);
    c21->cd(4);
    hDalitz_sideband_bin4->Draw("colz");
    cont_down->Draw("lsame");
    cont_up->Draw("lsame");
 */

}
