{

    TLegend *l = new TLegend(.7,.75,.89,.89);

    TFile f1("MuMuPiK_Jpsi_MuOnia2012ABCD_BkgAnalysis.root");

    TCanvas *c11 = new TCanvas("c11","c11",1050,1050);
    //hjpsiKPiMassBaseSelAlt_hard->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt_hard->SetMinimum(0.0);
    //hjpsiKPiMassNoPhi_hard->SetMaximum(17000);
    hjpsiKPiMassNoPhi_hard->SetMinimum(0.0);
    hjpsiKPiMassBaseSelAlt_hard->Draw();
    hjpsiKPiMassNoPhi_hard->SetLineColor(kRed);
    hjpsiKPiMassNoPhi_hard->Draw("same");
    hjpsiKPiMassNoPhi_discard_hard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard_hard->Draw("same");
    
    TLegend *l = new TLegend(.60,.60,.89,.73);
    l->AddEntry(hjpsiKPiMassBaseSelAlt_hard,"before Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi_hard,"after Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi_discard_hard, "Rejected events", "F");
    l->SetBorderSize(0);
    l->SetTextSize(0.025);
    l->Draw();
    c11->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiK_compare_hard.png");
    
    TCanvas *c12 = new TCanvas("c12","c12",1050,1050);
    hjpsiKKMassBaseSelAlt_hard->SetMinimum(0.0);
    hjpsiKKMassBaseSelAlt_hard->Draw();
    c12->SaveAs("Bkg_MuOnia2012ABCD_MuMuKK_hard.png");
    TCanvas *c13 = new TCanvas("c13","c13",1050,1050);
    hjpsiPiPiMassBaseSelAlt_hard->SetMinimum(0.0);
    hjpsiPiPiMassBaseSelAlt_hard->Draw();
    c13->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiPi_hard.png");
    TCanvas *c14 = new TCanvas("c14","c14",1050,1050);
    hjpsiKProtonMassBaseSelAlt_hard->SetMinimum(0.0);
    hjpsiKProtonMassBaseSelAlt_hard->Draw();
    c14->SaveAs("Bkg_MuOnia2012ABCD_MuMuKProton_hard.png");
    TCanvas *c15 = new TCanvas("c15","c15",1050,1050);
    hjpsiPiProtonMassBaseSelAlt_hard->SetMinimum(0.0);
    hjpsiPiProtonMassBaseSelAlt_hard->Draw();
    c15->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiProton_hard.png");
    TCanvas *c16 = new TCanvas("c16","c16",1050,1050);
    Int_t bxmax=hKPiMass_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_hard->GetXaxis()->FindBin(0.0);
    hKPiMass_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_hard->Draw();
    hKPiMass_peak_hard->SetLineColor(kRed);
    hKPiMass_peak_hard->Draw("same");
    TLegend *ll = new TLegend(.60,.60,.89,.73);
    ll->AddEntry(hKPiMass_hard,"All entries","L");
    ll->AddEntry(hKPiMass_peak_hard,"under B0 peak","L");
    ll->SetBorderSize(0);
    ll->SetTextSize(0.025);
    ll->Draw();
    c16->SaveAs("Bkg_MuOnia2012ABCD_KPi_all_hard.png");
    TCanvas *c17 = new TCanvas("c17","c17",1050,1050);
    Int_t bxmax=hPiPiMass_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_hard->GetXaxis()->FindBin(0.0);
    hPiPiMass_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_hard->Draw();
    hPiPiMass_peak_hard->SetLineColor(kRed);
    hPiPiMass_peak_hard->Draw("same");
    ll->Draw();
    c17->SaveAs("Bkg_MuOnia2012ABCD_PiPi_all_hard.png");
    TCanvas *c18 = new TCanvas("c18","c18",1050,1050);
    Int_t bxmax=hKKMass_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_hard->GetXaxis()->FindBin(0.0);
    hKKMass_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_hard->Draw();
    hKKMass_peak_hard->SetLineColor(kRed);
    hKKMass_peak_hard->Draw("same");
    ll->Draw();
    c18->SaveAs("Bkg_MuOnia2012ABCD_KK_all_hard.png");
    TCanvas *c19 = new TCanvas("c19","c19",1050,1050);
    Int_t bxmax=hKProtonMass_hard->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_hard->GetXaxis()->FindBin(0.0);
    hKProtonMass_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_hard->Draw();
    hKProtonMass_peak_hard->SetLineColor(kRed);
    hKProtonMass_peak_hard->Draw("same");
    ll->Draw();
    c19->SaveAs("Bkg_MuOnia2012ABCD_KProton_all_hard.png");
    TCanvas *c110 = new TCanvas("c110","c110",1050,1050);
    Int_t bxmax=hPiProtonMass_hard->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_hard->GetXaxis()->FindBin(0.0);
    hPiProtonMass_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_hard->Draw();
    hPiProtonMass_peak_hard->SetLineColor(kRed);
    hPiProtonMass_peak_hard->Draw("same");
    ll->Draw();
    c110->SaveAs("Bkg_MuOnia2012ABCD_PiProton_all_hard.png");
    TCanvas *c111 = new TCanvas("c111","c111",1050,1050);
    Int_t bxmax=hKPiMass_peak_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak_hard->GetXaxis()->FindBin(0.0);
    hKPiMass_peak_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak_hard->Draw();
    c111->SaveAs("Bkg_MuOnia2012ABCD_KPi_peak_hard.png");
    TCanvas *c112 = new TCanvas("c112","c112",1050,1050);
    Int_t bxmax=hPiPiMass_peak_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak_hard->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak_hard->Draw();
    c112->SaveAs("Bkg_MuOnia2012ABCD_PiPi_peak_hard.png");
    TCanvas *c113 = new TCanvas("c113","c113",1050,1050);
    Int_t bxmax=hKKMass_peak_hard->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak_hard->GetXaxis()->FindBin(0.0);
    hKKMass_peak_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak_hard->Draw();
    c113->SaveAs("Bkg_MuOnia2012ABCD_KK_peak_hard.png");
    TCanvas *c114 = new TCanvas("c114","c114",1050,1050);
    Int_t bxmax=hKProtonMass_peak_hard->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak_hard->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak_hard->Draw();
    c114->SaveAs("Bkg_MuOnia2012ABCD_KProton_peak_hard.png");
    TCanvas *c115 = new TCanvas("c115","c115",1050,1050);
    Int_t bxmax=hPiProtonMass_peak_hard->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak_hard->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak_hard->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak_hard->Draw();
    c115->SaveAs("Bkg_MuOnia2012ABCD_PiProton_peak_hard.png");
    
    TCanvas *c116 = new TCanvas("c116","c116",1050,1050);
    hJpsiKPi_JpsiKKBaseSelAlt_hard->Draw("colz");
    c116->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiKK_hard.png");
    TCanvas *c117 = new TCanvas("c117","c117",1050,1050);
    hJpsiKPi_JpsiPiPiBaseSelAlt_hard->Draw("colz");
    c117->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiPiPi_hard.png");
    TCanvas *c118 = new TCanvas("c118","c118",1050,1050);
    hJpsiKPi_JpsiPiProtonBaseSelAlt_hard->Draw("colz");
    c118->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiPiProton_hard.png");
    TCanvas *c119 = new TCanvas("c119","c119",1050,1050);
    hJpsiKPi_JpsiKProtonBaseSelAlt_hard->Draw("colz");
    c119->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiKProton_hard.png");
    f1->Close();
    

}
