{

    TLegend *l = new TLegend(.7,.75,.89,.89);

    TFile f1("MuMuPiK_Jpsi_MuOnia2012ABCD_BkgAnalysis.root");

    TCanvas *c11 = new TCanvas("c11","c11",1050,1050);
    //hjpsiKPiMassBaseSelAlt->SetMaximum(17000);
    hjpsiKPiMassBaseSelAlt->SetMinimum(0.0);
    //hjpsiKPiMassNoPhi->SetMaximum(17000);
    hjpsiKPiMassNoPhi->SetMinimum(0.0);
    hjpsiKPiMassBaseSelAlt->Draw();
    hjpsiKPiMassNoPhi->SetLineColor(kRed);
    hjpsiKPiMassNoPhi->Draw("same");
    hjpsiKPiMassNoPhi_discard->SetFillColor( kRed);
    hjpsiKPiMassNoPhi_discard->Draw("same");
    
    TLegend *l = new TLegend(.60,.60,.89,.73);
    l->AddEntry(hjpsiKPiMassBaseSelAlt,"before Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi,"after Phi->KK removal","L");
    l->AddEntry(hjpsiKPiMassNoPhi_discard, "Rejected events", "F");
    l->SetBorderSize(0);
    l->SetTextSize(0.025);
    l->Draw();
    c11->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiK_compare.png");
    
    TCanvas *c12 = new TCanvas("c12","c12",1050,1050);
    hjpsiKKMassBaseSelAlt->SetMinimum(0.0);
    hjpsiKKMassBaseSelAlt->Draw();
    c12->SaveAs("Bkg_MuOnia2012ABCD_MuMuKK.png");
    TCanvas *c13 = new TCanvas("c13","c13",1050,1050);
    hjpsiPiPiMassBaseSelAlt->SetMinimum(0.0);
    hjpsiPiPiMassBaseSelAlt->Draw();
    c13->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiPi.png");
    TCanvas *c14 = new TCanvas("c14","c14",1050,1050);
    hjpsiKProtonMassBaseSelAlt->SetMinimum(0.0);
    hjpsiKProtonMassBaseSelAlt->Draw();
    c14->SaveAs("Bkg_MuOnia2012ABCD_MuMuKProton.png");
    TCanvas *c15 = new TCanvas("c15","c15",1050,1050);
    hjpsiPiProtonMassBaseSelAlt->SetMinimum(0.0);
    hjpsiPiProtonMassBaseSelAlt->Draw();
    c15->SaveAs("Bkg_MuOnia2012ABCD_MuMuPiProton.png");
    TCanvas *c16 = new TCanvas("c16","c16",1050,1050);
    Int_t bxmax=hKPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass->GetXaxis()->FindBin(0.0);
    hKPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass->Draw();
    hKPiMass_peak->SetLineColor(kRed);
    hKPiMass_peak->Draw("same");
    TLegend *ll = new TLegend(.60,.60,.89,.73);
    ll->AddEntry(hKPiMass,"All entries","L");
    ll->AddEntry(hKPiMass_peak,"under B0 peak","L");
    ll->SetBorderSize(0);
    ll->SetTextSize(0.025);
    ll->Draw();
    c16->SaveAs("Bkg_MuOnia2012ABCD_KPi_all.png");
    TCanvas *c17 = new TCanvas("c17","c17",1050,1050);
    Int_t bxmax=hPiPiMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass->GetXaxis()->FindBin(0.0);
    hPiPiMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass->Draw();
    hPiPiMass_peak->SetLineColor(kRed);
    hPiPiMass_peak->Draw("same");
    ll->Draw();
    c17->SaveAs("Bkg_MuOnia2012ABCD_PiPi_all.png");
    TCanvas *c18 = new TCanvas("c18","c18",1050,1050);
    Int_t bxmax=hKKMass->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass->GetXaxis()->FindBin(0.0);
    hKKMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass->Draw();
    hKKMass_peak->SetLineColor(kRed);
    hKKMass_peak->Draw("same");
    ll->Draw();
    c18->SaveAs("Bkg_MuOnia2012ABCD_KK_all.png");
    TCanvas *c19 = new TCanvas("c19","c19",1050,1050);
    Int_t bxmax=hKProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass->GetXaxis()->FindBin(0.0);
    hKProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass->Draw();
    hKProtonMass_peak->SetLineColor(kRed);
    hKProtonMass_peak->Draw("same");
    ll->Draw();
    c19->SaveAs("Bkg_MuOnia2012ABCD_KProton_all.png");
    TCanvas *c110 = new TCanvas("c110","c110",1050,1050);
    Int_t bxmax=hPiProtonMass->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass->GetXaxis()->FindBin(0.0);
    hPiProtonMass->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass->Draw();
    hPiProtonMass_peak->SetLineColor(kRed);
    hPiProtonMass_peak->Draw("same");
    ll->Draw();
    c110->SaveAs("Bkg_MuOnia2012ABCD_PiProton_all.png");
    TCanvas *c111 = new TCanvas("c111","c111",1050,1050);
    Int_t bxmax=hKPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKPiMass_peak->GetXaxis()->FindBin(0.0);
    hKPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKPiMass_peak->Draw();
    c111->SaveAs("Bkg_MuOnia2012ABCD_KPi_peak.png");
    TCanvas *c112 = new TCanvas("c112","c112",1050,1050);
    Int_t bxmax=hPiPiMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hPiPiMass_peak->GetXaxis()->FindBin(0.0);
    hPiPiMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiPiMass_peak->Draw();
    c112->SaveAs("Bkg_MuOnia2012ABCD_PiPi_peak.png");
    TCanvas *c113 = new TCanvas("c113","c113",1050,1050);
    Int_t bxmax=hKKMass_peak->GetXaxis()->FindBin(3.0);
    Int_t bxmin=hKKMass_peak->GetXaxis()->FindBin(0.0);
    hKKMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKKMass_peak->Draw();
    c113->SaveAs("Bkg_MuOnia2012ABCD_KK_peak.png");
    TCanvas *c114 = new TCanvas("c114","c114",1050,1050);
    Int_t bxmax=hKProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hKProtonMass_peak->GetXaxis()->FindBin(0.0);
    hKProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hKProtonMass_peak->Draw();
    c114->SaveAs("Bkg_MuOnia2012ABCD_KProton_peak.png");
    TCanvas *c115 = new TCanvas("c115","c115",1050,1050);
    Int_t bxmax=hPiProtonMass_peak->GetXaxis()->FindBin(4.0);
    Int_t bxmin=hPiProtonMass_peak->GetXaxis()->FindBin(0.0);
    hPiProtonMass_peak->GetXaxis()->SetRange(bxmin,bxmax);
    hPiProtonMass_peak->Draw();
    c115->SaveAs("Bkg_MuOnia2012ABCD_PiProton_peak.png");
    
    TCanvas *c116 = new TCanvas("c116","c116",1050,1050);
    hJpsiKPi_JpsiKKBaseSelAlt->Draw("colz");
    c116->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiKK.png");
    TCanvas *c117 = new TCanvas("c117","c117",1050,1050);
    hJpsiKPi_JpsiPiPiBaseSelAlt->Draw("colz");
    c117->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiPiPi.png");
    TCanvas *c118 = new TCanvas("c118","c118",1050,1050);
    hJpsiKPi_JpsiPiProtonBaseSelAlt->Draw("colz");
    c118->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiPiProton.png");
    TCanvas *c119 = new TCanvas("c119","c119",1050,1050);
    hJpsiKPi_JpsiKProtonBaseSelAlt->Draw("colz");
    c119->SaveAs("Bkg_MuOnia2012ABCD_JpsiKPi_JpsiKProton.png");
    f1->Close();
    
}
