{
//=========Macro generated from canvas: c/c
//=========  (Tue Nov 24 18:54:53 2015) by ROOT version5.34/32
   TCanvas *c = new TCanvas("c", "c",80,121,808,635);
   c->Range(5.1125,0.6257433,5.4875,4.36831);
   c->SetFillColor(0);
   c->SetBorderMode(0);
   c->SetBorderSize(2);
   c->SetLogy();
   c->SetFrameBorderMode(0);
   c->SetFrameBorderMode(0);
   
   TH1F *hjpsiKPiMassSelAltZoom = new TH1F("hjpsiKPiMassSelAltZoom","hjpsiKPiMassSel ALTERNATIVE ZOOM",90,5.15,5.45);
   hjpsiKPiMassSelAltZoom->SetBinContent(0,24091);
   hjpsiKPiMassSelAltZoom->SetBinContent(1,1601);
   hjpsiKPiMassSelAltZoom->SetBinContent(2,1572);
   hjpsiKPiMassSelAltZoom->SetBinContent(3,1525);
   hjpsiKPiMassSelAltZoom->SetBinContent(4,1581);
   hjpsiKPiMassSelAltZoom->SetBinContent(5,1599);
   hjpsiKPiMassSelAltZoom->SetBinContent(6,1632);
   hjpsiKPiMassSelAltZoom->SetBinContent(7,1575);
   hjpsiKPiMassSelAltZoom->SetBinContent(8,1620);
   hjpsiKPiMassSelAltZoom->SetBinContent(9,1626);
   hjpsiKPiMassSelAltZoom->SetBinContent(10,1591);
   hjpsiKPiMassSelAltZoom->SetBinContent(11,1680);
   hjpsiKPiMassSelAltZoom->SetBinContent(12,1593);
   hjpsiKPiMassSelAltZoom->SetBinContent(13,1572);
   hjpsiKPiMassSelAltZoom->SetBinContent(14,1599);
   hjpsiKPiMassSelAltZoom->SetBinContent(15,1682);
   hjpsiKPiMassSelAltZoom->SetBinContent(16,1618);
   hjpsiKPiMassSelAltZoom->SetBinContent(17,1616);
   hjpsiKPiMassSelAltZoom->SetBinContent(18,1680);
   hjpsiKPiMassSelAltZoom->SetBinContent(19,1587);
   hjpsiKPiMassSelAltZoom->SetBinContent(20,1635);
   hjpsiKPiMassSelAltZoom->SetBinContent(21,1666);
   hjpsiKPiMassSelAltZoom->SetBinContent(22,1646);
   hjpsiKPiMassSelAltZoom->SetBinContent(23,1618);
   hjpsiKPiMassSelAltZoom->SetBinContent(24,1610);
   hjpsiKPiMassSelAltZoom->SetBinContent(25,1727);
   hjpsiKPiMassSelAltZoom->SetBinContent(26,1780);
   hjpsiKPiMassSelAltZoom->SetBinContent(27,1825);
   hjpsiKPiMassSelAltZoom->SetBinContent(28,1926);
   hjpsiKPiMassSelAltZoom->SetBinContent(29,1985);
   hjpsiKPiMassSelAltZoom->SetBinContent(30,2009);
   hjpsiKPiMassSelAltZoom->SetBinContent(31,2177);
   hjpsiKPiMassSelAltZoom->SetBinContent(32,2472);
   hjpsiKPiMassSelAltZoom->SetBinContent(33,2680);
   hjpsiKPiMassSelAltZoom->SetBinContent(34,3198);
   hjpsiKPiMassSelAltZoom->SetBinContent(35,3566);
   hjpsiKPiMassSelAltZoom->SetBinContent(36,4000);
   hjpsiKPiMassSelAltZoom->SetBinContent(37,4455);
   hjpsiKPiMassSelAltZoom->SetBinContent(38,5020);
   hjpsiKPiMassSelAltZoom->SetBinContent(39,5206);
   hjpsiKPiMassSelAltZoom->SetBinContent(40,4923);
   hjpsiKPiMassSelAltZoom->SetBinContent(41,4663);
   hjpsiKPiMassSelAltZoom->SetBinContent(42,4386);
   hjpsiKPiMassSelAltZoom->SetBinContent(43,3665);
   hjpsiKPiMassSelAltZoom->SetBinContent(44,3380);
   hjpsiKPiMassSelAltZoom->SetBinContent(45,2990);
   hjpsiKPiMassSelAltZoom->SetBinContent(46,2636);
   hjpsiKPiMassSelAltZoom->SetBinContent(47,2369);
   hjpsiKPiMassSelAltZoom->SetBinContent(48,2183);
   hjpsiKPiMassSelAltZoom->SetBinContent(49,2062);
   hjpsiKPiMassSelAltZoom->SetBinContent(50,1986);
   hjpsiKPiMassSelAltZoom->SetBinContent(51,1858);
   hjpsiKPiMassSelAltZoom->SetBinContent(52,1756);
   hjpsiKPiMassSelAltZoom->SetBinContent(53,1630);
   hjpsiKPiMassSelAltZoom->SetBinContent(54,1646);
   hjpsiKPiMassSelAltZoom->SetBinContent(55,1561);
   hjpsiKPiMassSelAltZoom->SetBinContent(56,1569);
   hjpsiKPiMassSelAltZoom->SetBinContent(57,1628);
   hjpsiKPiMassSelAltZoom->SetBinContent(58,1544);
   hjpsiKPiMassSelAltZoom->SetBinContent(59,1525);
   hjpsiKPiMassSelAltZoom->SetBinContent(60,1505);
   hjpsiKPiMassSelAltZoom->SetBinContent(61,1557);
   hjpsiKPiMassSelAltZoom->SetBinContent(62,1491);
   hjpsiKPiMassSelAltZoom->SetBinContent(63,1444);
   hjpsiKPiMassSelAltZoom->SetBinContent(64,1477);
   hjpsiKPiMassSelAltZoom->SetBinContent(65,1375);
   hjpsiKPiMassSelAltZoom->SetBinContent(66,1449);
   hjpsiKPiMassSelAltZoom->SetBinContent(67,1434);
   hjpsiKPiMassSelAltZoom->SetBinContent(68,1285);
   hjpsiKPiMassSelAltZoom->SetBinContent(69,1376);
   hjpsiKPiMassSelAltZoom->SetBinContent(70,1334);
   hjpsiKPiMassSelAltZoom->SetBinContent(71,1317);
   hjpsiKPiMassSelAltZoom->SetBinContent(72,1267);
   hjpsiKPiMassSelAltZoom->SetBinContent(73,1287);
   hjpsiKPiMassSelAltZoom->SetBinContent(74,1331);
   hjpsiKPiMassSelAltZoom->SetBinContent(75,1153);
   hjpsiKPiMassSelAltZoom->SetBinContent(76,1201);
   hjpsiKPiMassSelAltZoom->SetBinContent(77,1291);
   hjpsiKPiMassSelAltZoom->SetBinContent(78,1226);
   hjpsiKPiMassSelAltZoom->SetBinContent(79,1230);
   hjpsiKPiMassSelAltZoom->SetBinContent(80,1104);
   hjpsiKPiMassSelAltZoom->SetBinContent(81,1156);
   hjpsiKPiMassSelAltZoom->SetBinContent(82,1182);
   hjpsiKPiMassSelAltZoom->SetBinContent(83,1126);
   hjpsiKPiMassSelAltZoom->SetBinContent(84,1086);
   hjpsiKPiMassSelAltZoom->SetBinContent(85,1010);
   hjpsiKPiMassSelAltZoom->SetBinContent(86,1008);
   hjpsiKPiMassSelAltZoom->SetBinContent(87,984);
   hjpsiKPiMassSelAltZoom->SetBinContent(88,919);
   hjpsiKPiMassSelAltZoom->SetBinContent(89,777);
   hjpsiKPiMassSelAltZoom->SetBinContent(90,798);
   hjpsiKPiMassSelAltZoom->SetBinContent(91,7058);
   hjpsiKPiMassSelAltZoom->SetMinimum(10);
   hjpsiKPiMassSelAltZoom->SetEntries(202039);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("hjpsiKPiMassSelAltZoom");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 202039 ");
   text = ptstats->AddText("Mean  =  5.288");
   text = ptstats->AddText("RMS   = 0.0736");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hjpsiKPiMassSelAltZoom->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hjpsiKPiMassSelAltZoom);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   hjpsiKPiMassSelAltZoom->SetLineColor(ci);
   hjpsiKPiMassSelAltZoom->GetXaxis()->SetLabelFont(42);
   hjpsiKPiMassSelAltZoom->GetXaxis()->SetLabelSize(0.035);
   hjpsiKPiMassSelAltZoom->GetXaxis()->SetTitleSize(0.035);
   hjpsiKPiMassSelAltZoom->GetXaxis()->SetTitleFont(42);
   hjpsiKPiMassSelAltZoom->GetYaxis()->SetLabelFont(42);
   hjpsiKPiMassSelAltZoom->GetYaxis()->SetLabelSize(0.035);
   hjpsiKPiMassSelAltZoom->GetYaxis()->SetTitleSize(0.035);
   hjpsiKPiMassSelAltZoom->GetYaxis()->SetTitleFont(42);
   hjpsiKPiMassSelAltZoom->GetZaxis()->SetLabelFont(42);
   hjpsiKPiMassSelAltZoom->GetZaxis()->SetLabelSize(0.035);
   hjpsiKPiMassSelAltZoom->GetZaxis()->SetTitleSize(0.035);
   hjpsiKPiMassSelAltZoom->GetZaxis()->SetTitleFont(42);
   hjpsiKPiMassSelAltZoom->Draw("");
   
   TPaveText *pt = new TPaveText(0.198194,0.9342,0.801806,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("hjpsiKPiMassSel ALTERNATIVE ZOOM");
   pt->Draw();
   
   TH1F *hjpsiKPiMassBs = new TH1F("hjpsiKPiMassBs","hjpsiKPiMass in Bs signal region ",90,5.15,5.45);
   hjpsiKPiMassBs->SetBinContent(0,493);
   hjpsiKPiMassBs->SetBinContent(1,46);
   hjpsiKPiMassBs->SetBinContent(2,37);
   hjpsiKPiMassBs->SetBinContent(3,62);
   hjpsiKPiMassBs->SetBinContent(4,46);
   hjpsiKPiMassBs->SetBinContent(5,47);
   hjpsiKPiMassBs->SetBinContent(6,41);
   hjpsiKPiMassBs->SetBinContent(7,57);
   hjpsiKPiMassBs->SetBinContent(8,53);
   hjpsiKPiMassBs->SetBinContent(9,68);
   hjpsiKPiMassBs->SetBinContent(10,56);
   hjpsiKPiMassBs->SetBinContent(11,64);
   hjpsiKPiMassBs->SetBinContent(12,59);
   hjpsiKPiMassBs->SetBinContent(13,73);
   hjpsiKPiMassBs->SetBinContent(14,81);
   hjpsiKPiMassBs->SetBinContent(15,82);
   hjpsiKPiMassBs->SetBinContent(16,70);
   hjpsiKPiMassBs->SetBinContent(17,64);
   hjpsiKPiMassBs->SetBinContent(18,75);
   hjpsiKPiMassBs->SetBinContent(19,87);
   hjpsiKPiMassBs->SetBinContent(20,88);
   hjpsiKPiMassBs->SetBinContent(21,82);
   hjpsiKPiMassBs->SetBinContent(22,105);
   hjpsiKPiMassBs->SetBinContent(23,104);
   hjpsiKPiMassBs->SetBinContent(24,89);
   hjpsiKPiMassBs->SetBinContent(25,106);
   hjpsiKPiMassBs->SetBinContent(26,104);
   hjpsiKPiMassBs->SetBinContent(27,109);
   hjpsiKPiMassBs->SetBinContent(28,90);
   hjpsiKPiMassBs->SetBinContent(29,91);
   hjpsiKPiMassBs->SetBinContent(30,112);
   hjpsiKPiMassBs->SetBinContent(31,98);
   hjpsiKPiMassBs->SetBinContent(32,117);
   hjpsiKPiMassBs->SetBinContent(33,102);
   hjpsiKPiMassBs->SetBinContent(34,115);
   hjpsiKPiMassBs->SetBinContent(35,123);
   hjpsiKPiMassBs->SetBinContent(36,133);
   hjpsiKPiMassBs->SetBinContent(37,118);
   hjpsiKPiMassBs->SetBinContent(38,132);
   hjpsiKPiMassBs->SetBinContent(39,132);
   hjpsiKPiMassBs->SetBinContent(40,100);
   hjpsiKPiMassBs->SetBinContent(41,123);
   hjpsiKPiMassBs->SetBinContent(42,104);
   hjpsiKPiMassBs->SetBinContent(43,80);
   hjpsiKPiMassBs->SetBinContent(44,102);
   hjpsiKPiMassBs->SetBinContent(45,72);
   hjpsiKPiMassBs->SetBinContent(46,84);
   hjpsiKPiMassBs->SetBinContent(47,46);
   hjpsiKPiMassBs->SetBinContent(48,59);
   hjpsiKPiMassBs->SetBinContent(49,39);
   hjpsiKPiMassBs->SetBinContent(50,28);
   hjpsiKPiMassBs->SetBinContent(51,15);
   hjpsiKPiMassBs->SetBinContent(52,19);
   hjpsiKPiMassBs->SetBinContent(53,10);
   hjpsiKPiMassBs->SetBinContent(54,7);
   hjpsiKPiMassBs->SetBinContent(55,4);
   hjpsiKPiMassBs->SetBinContent(56,5);
   hjpsiKPiMassBs->SetBinContent(57,3);
   hjpsiKPiMassBs->SetBinContent(58,1);
   hjpsiKPiMassBs->SetEntries(4712);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("hjpsiKPiMassBs");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 4712   ");
   text = ptstats->AddText("Mean  =  5.241");
   text = ptstats->AddText("RMS   = 0.04327");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   hjpsiKPiMassBs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(hjpsiKPiMassBs);
   hjpsiKPiMassBs->SetLineColor(2);
   hjpsiKPiMassBs->GetXaxis()->SetLabelFont(42);
   hjpsiKPiMassBs->GetXaxis()->SetLabelSize(0.035);
   hjpsiKPiMassBs->GetXaxis()->SetTitleSize(0.035);
   hjpsiKPiMassBs->GetXaxis()->SetTitleFont(42);
   hjpsiKPiMassBs->GetYaxis()->SetLabelFont(42);
   hjpsiKPiMassBs->GetYaxis()->SetLabelSize(0.035);
   hjpsiKPiMassBs->GetYaxis()->SetTitleSize(0.035);
   hjpsiKPiMassBs->GetYaxis()->SetTitleFont(42);
   hjpsiKPiMassBs->GetZaxis()->SetLabelFont(42);
   hjpsiKPiMassBs->GetZaxis()->SetLabelSize(0.035);
   hjpsiKPiMassBs->GetZaxis()->SetTitleSize(0.035);
   hjpsiKPiMassBs->GetZaxis()->SetTitleFont(42);
   hjpsiKPiMassBs->Draw("same");
   c->Modified();
   c->cd();
   c->SetSelected(c);
}
